export const CHARACTERS = 'CHARACTERS';
export const EPISODES = 'EPISODES';
export const LOCATIONS = 'LOCATIONS';
export const SETTING = 'SETTING';
export const TABNAVIGATOR = 'TABNAVIGATOR';
export const CHARACTERDETAIL = 'CHARACTERDETAIL';
export const FILTERCHARACTERS = 'FILTERCHARACTERS';
export const SEARCHCHARACTERS = 'SEARCHCHARACTERS';
